# Generated by Django 2.0.7 on 2018-07-16 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('measurement', models.CharField(choices=[('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('oz', 'fluid ounce'), ('ml', 'millilitre'), ('l', 'litre'), ('ib', 'pound'), ('oz', 'ounce'), ('mg', 'milligram'), ('g', 'gram'), ('kg', 'kilogram'), ('cm', 'centimeter'), ('sml', 'small'), ('med', 'medium'), ('lrg', 'large')], max_length=30)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('intro', models.CharField(max_length=180)),
                ('image', models.ImageField(upload_to='meal_images/')),
                ('preparation_time', models.IntegerField()),
                ('cooking_time', models.IntegerField()),
                ('user_rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=120)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Meal')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='meal',
            field=models.ManyToManyField(to='recipe.Meal'),
        ),
        migrations.AddField(
            model_name='comment',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Meal'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='meal',
            field=models.ManyToManyField(to='recipe.Meal'),
        ),
    ]
