# Generated by Django 2.0.7 on 2018-07-16 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='step',
            name='meal',
        ),
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.ManyToManyField(to='recipe.Category'),
        ),
        migrations.AddField(
            model_name='meal',
            name='comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='recipe.Comment'),
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredient',
            field=models.ManyToManyField(to='recipe.Ingredient'),
        ),
        migrations.AddField(
            model_name='meal',
            name='step',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='recipe.Step'),
        ),
    ]
