# Generated by Django 2.0.7 on 2018-07-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20180716_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(default='meal_images/no_image.jpeg', upload_to='meal_images/'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='user_rating',
            field=models.IntegerField(default=0),
        ),
    ]
