# Generated by Django 2.0.7 on 2018-07-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20180716_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(default='static/recipe/images/no_image.jpeg', upload_to='static/recipe/images/'),
        ),
    ]
