# Generated by Django 2.0.7 on 2018-07-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20180722_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(default='recipe/images/no_image.jpeg', upload_to='recipe/images/'),
        ),
    ]
