# Generated by Django 2.0.7 on 2018-07-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0002_auto_20180719_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premium',
            name='user',
        ),
        migrations.DeleteModel(
            name='Premium',
        ),
    ]
