# Generated by Django 2.0.7 on 2018-07-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20180716_1348'),
        ('premium', '0008_delete_premiumuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='favourites',
            field=models.ManyToManyField(to='recipe.Meal'),
        ),
    ]
